"use client";

import { Suspense, useEffect, useState } from "react";
import { useSearchParams } from "next/navigation";
import { Clipboard, Download, Sparkles } from "lucide-react";

import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { StatusPanel } from "@/components/ui/status";
import { generateReport } from "@/lib/api";

function ReportPageContent() {
  const params = useSearchParams();
  const [runId, setRunId] = useState(Number(params.get("runId")) || 0);
  const [markdown, setMarkdown] = useState("");
  const [generatedBy, setGeneratedBy] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const generate = async () => {
    if (!runId) return;
    setLoading(true);
    setError(null);
    try {
      const report = await generateReport(runId);
      setMarkdown(report.markdown);
      setGeneratedBy(report.generated_by);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Report generation failed");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (runId) void generate();
  }, [runId]);

  const download = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = url;
    anchor.download = `simulation-run-${runId}-report.md`;
    anchor.click();
    URL.revokeObjectURL(url);
  };

  return (
    <main className="mx-auto max-w-7xl px-5 py-8">
      <p className="text-sm font-bold uppercase text-accent">AI-assisted Report</p>
      <h1 className="mt-2 text-3xl font-black">Experiment Report</h1>
      {error && <StatusPanel className="mt-6" title="Report unavailable" message={error} variant="error" />}
      <div className="mt-6 grid gap-5 lg:grid-cols-[320px_1fr]">
        <Card>
          <CardHeader><CardTitle>Report Source</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            <input
              type="number"
              value={runId || ""}
              onChange={(event) => setRunId(Number(event.target.value))}
              placeholder="Simulation run id"
              className="h-10 w-full rounded-[6px] border border-border px-3"
            />
            <Button onClick={generate} className="w-full" disabled={!runId || loading}><Sparkles className="h-4 w-4" /> {loading ? "Generating" : "Generate"}</Button>
            <Button onClick={() => navigator.clipboard.writeText(markdown)} variant="secondary" className="w-full" disabled={!markdown}>
              <Clipboard className="h-4 w-4" /> Copy Markdown
            </Button>
            <Button onClick={download} variant="secondary" className="w-full" disabled={!markdown}>
              <Download className="h-4 w-4" /> Export .md
            </Button>
            {generatedBy && <p className="text-xs text-muted">Generated by {generatedBy}</p>}
          </CardContent>
        </Card>
        <Card>
          <CardHeader><CardTitle>Markdown Preview</CardTitle></CardHeader>
          <CardContent>
            <pre className="min-h-[540px] whitespace-pre-wrap rounded-[8px] border border-border bg-stone-950 p-5 text-sm leading-6 text-stone-100">
              {markdown || "No report generated. Enter a simulation run id or launch this page from the Results dashboard."}
            </pre>
          </CardContent>
        </Card>
      </div>
    </main>
  );
}

export default function ReportPage() {
  return (
    <Suspense fallback={<main className="mx-auto max-w-7xl px-5 py-8"><StatusPanel title="Loading report" message="Preparing report generation controls." /></main>}>
      <ReportPageContent />
    </Suspense>
  );
}
